messages:
  null-potion: '&cЗелье или предмет на который Вы нажали не может использоваться в смешивании.'
  no-potions: '&cДля смешивания нужно 2 зелья.'
  successful: '&aЗелье успешно смешано.'
  nope: '&cНеудача. Алхимик не смог смешать зелья.'
  water-mix: '&cНельзя смешать воду.'
  max-chance: '&cВаш шанс достиг максимальной отметки. Пора рискнуть.'
  potion-level: '&cУровень зелья слишком высок.'
  no-money: '&cУ Вас недостаточно денег для этого действия.'

potion-name: '&dВедьмино снадобье'
potion-color: '159;160;255' # RGB цвета для зелья, формат: R;G;B
unlimited-mix: true # Если true, можно смешивать более 2 зелий; если false, только 2 зелья

# Заблокированные эффекты зелий (формат: НАЗВАНИЕ_ЭФФЕКТА:УРОВЕНЬ)
blocked-effects:
  - 'STRENGTH:3'
  - 'SPEED:3'

enable-metrics: true # Включение bStats для статистики плагина